/**
 * Created by zhengguorong on 16/6/27.
 */
export const FETCH_COMING_SOON_SUCCESS='FETCH_COMING_SOON_SUCCESS'
export const FETCH_COMING_SOON_FAIL='FETCH_COMING_SOON_FAIL'
export const FETCH_NOW_PLAYING_SUCCESS='FETCH_NOW_PLAYING_SUCCESS'
export const FETCH_NOW_PLAYING_FAIL='FETCH_NOW_PLAYING_FAIL'
export const FETCH_DETAIL_SUCCESS='FETCH_DETAIL_SUCCESS'
export const FETCH_BILLBOARD_SUCCESS='FETCH_BILLBOARD_SUCCESS'

export const CHANGE_LEFTNAV_STATE='CHANGE_LEFTNAV_STATE'
export const START_LOADING = 'START_LOADING'
export const FINISH_LOADING= 'FINISH_LOADING'
export const CUR_TAB = 'CUR_TAB'
