export const FETCH_COMING_SOON_SUCCESS = 'FETCH_COMING_SOON_SUCCESS'
export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS'
